version: "3"
services:
  front:
    build:
      context: .
      dockerfile: front.Dockerfile
    ports : 
     - "4200:4200"
  back:
    build:
      context: .
      dockerfile: back.Dockerfile
    ports:
    - "4050:4050"
